import 'package:contacts_flutter/models/contacts/contacts_model.dart';

List<Contact> listOfContacts = [
  Contact(
    id: 1,
    firstName: "Tris",
    lastName: "Pusey",
    phoneNumber: "177-947-9423",
    emailAddress: "tpusey0@indiegogo.com",
  ),
  Contact(
    id: 2,
    firstName: "Gunilla",
    lastName: "Stetson",
    phoneNumber: "926-326-2120",
    emailAddress: "gstetson1@themeforest.net",
  ),
  Contact(
    id: 3,
    firstName: "Florinda",
    lastName: "Stummeyer",
    phoneNumber: "301-380-8446",
    emailAddress: "fstummeyer2@prnewswire.com",
  ),
  Contact(
    id: 4,
    firstName: "Zak",
    lastName: "Steen",
    phoneNumber: "263-153-9491",
    emailAddress: "zsteen3@plala.or.jp",
  ),
  Contact(
    id: 5,
    firstName: "Allie",
    lastName: "Dayley",
    phoneNumber: "286-239-4464",
    emailAddress: "adayley4@shop-pro.jp",
  ),
  Contact(
    id: 6,
    firstName: "Gratia",
    lastName: "Kempe",
    phoneNumber: "862-407-4782",
    emailAddress: "gkempe5@rediff.com",
  ),
  Contact(
    id: 7,
    firstName: "Rosanne",
    lastName: "Audibert",
    phoneNumber: "368-843-0037",
    emailAddress: "raudibert6@eventbrite.com",
  ),
  Contact(
    id: 8,
    firstName: "Frederich",
    lastName: "Crilly",
    phoneNumber: "803-773-6458",
    emailAddress: "fcrilly7@opera.com",
  ),
  Contact(
    id: 9,
    firstName: "Akim",
    lastName: "Axcel",
    phoneNumber: "661-282-6676",
    emailAddress: "aaxcel8@merriam-webster.com",
  ),
  Contact(
    id: 10,
    firstName: "Malinda",
    lastName: "Sessuns",
    phoneNumber: "389-626-1613",
    emailAddress: "msessuns9@theatlantic.com",
  ),
  Contact(
    id: 11,
    firstName: "Domenic",
    lastName: "Blackstock",
    phoneNumber: "242-250-2059",
    emailAddress: "dblackstocka@redcross.org",
  ),
  Contact(
    id: 12,
    firstName: "Itch",
    lastName: "Pett",
    phoneNumber: "157-307-3096",
    emailAddress: "ipettb@edublogs.org",
  ),
  Contact(
    id: 13,
    firstName: "Judah",
    lastName: "Potapczuk",
    phoneNumber: "352-894-0345",
    emailAddress: "jpotapczukc@vk.com",
  ),
  Contact(
    id: 14,
    firstName: "Franchot",
    lastName: "Piggen",
    phoneNumber: "255-145-7027",
    emailAddress: "fpiggend@sogou.com",
  ),
  Contact(
    id: 15,
    firstName: "Mill",
    lastName: "Lillie",
    phoneNumber: "929-738-2116",
    emailAddress: "mlilliee@unicef.org",
  ),
  Contact(
    id: 16,
    firstName: "Kiele",
    lastName: "Tomkowicz",
    phoneNumber: "651-370-8306",
    emailAddress: "ktomkowiczf@youtu.be",
  ),
  Contact(
    id: 17,
    firstName: "Cherilyn",
    lastName: "Bottrill",
    phoneNumber: "655-685-6642",
    emailAddress: "cbottrillg@goodreads.com",
  ),
  Contact(
    id: 18,
    firstName: "Orion",
    lastName: "Cale",
    phoneNumber: "752-266-8870",
    emailAddress: "ocaleh@ca.gov",
  ),
  Contact(
    id: 19,
    firstName: "Philippa",
    lastName: "Coppo",
    phoneNumber: "214-675-7872",
    emailAddress: "pcoppoi@goo.gl",
  ),
  Contact(
    id: 20,
    firstName: "Pieter",
    lastName: "Janney",
    phoneNumber: "198-761-4495",
    emailAddress: "pjanneyj@seattletimes.com",
  ),
];
